POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Authn broo with billing account",
  "email": "authn@gmail.com",
  "address": "galle",
  "dateOfBirth": "2002-07-01",
  "registeredDate": "2026-07-01"
}